version: "3.6"

volumes:
  prometheus_data: {}

networks:
  monitor-net:
    driver: bridge

services:
  halo-serving:
    image: tensorflow/serving
    ports:
      - 8500:8500
      - 8501:8501
    volumes:
      # Model
      - type: bind
        source: ./models/FbDeepFace/
        target: /models/deepface
      # Configurations
      - type: bind
        source: ./serving.cfg
        target: /models/serving.cfg
    restart: on-failure
    command:
      - "--model_config_file=/models/serving.cfg"
      - "--allow_version_labels_for_unavailable_models=true"
  
  core:
    build:
      context: .
    # replicate `docker run -it` for dev.
    stdin_open: true
    tty: true
    # ----------------------------------
    depends_on:
      - halo-serving
    volumes:
      - .:/app
    restart: on-failure
    ports:
      - 9000:9000
    command: ["bash"]

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yaml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/etc/prometheus/console_libraries"
      - "--web.console.templates=/etc/prometheus/consoles"
      - "--storage.tsdb.retention.time=200h"
      - "--web.enable-lifecycle"
    restart: unless-stopped
    expose:
      - 9090
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"
