version: "3.6"

volumes:
  prometheus_data:
  grafana_data:

networks:
  monitor-net:
    driver: bridge
  haloserving-net:
    driver: bridge

services:
  halo-serving:
    image: tensorflow/serving
    ports:
      - 8500:8500
      - 8501:8501
    volumes:
      # Model
      - type: bind
        source: ./model_service/models/FbDeepFace/
        target: /models/deepface
      # Configurations
      - type: bind
        source: ./model_service/serving.conf
        target: /models/serving.conf
      # Prometheus config
      - type: bind
        source: ./model_service/monitoring.conf
        target: /models/monitoring.conf
    restart: on-failure
    networks:
      - monitor-net
      - haloserving-net
    command:
      - "--model_config_file=/models/serving.conf"
      - "--allow_version_labels_for_unavailable_models=true"
      - "--monitoring_config_file=/models/monitoring.conf"

  core:
    build:
      context: ./core_service
    # replicate `docker run -it` for dev.
    # stdin_open: true
    # tty: true
    # ----------------------------------
    depends_on:
      - halo-serving
        # volumes:
        # - ./core_service:/app
    networks:
      - haloserving-net
    restart: on-failure
    ports:
      - 9000:9000
        # command: ["bash"]

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./model_service/prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    ports:
      - 9090:9090
    command:
      - "--config.file=/etc/prometheus/prometheus.yaml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/etc/prometheus/console_libraries"
      - "--web.console.templates=/etc/prometheus/consoles"
      - "--storage.tsdb.retention.time=200h"
      - "--web.enable-lifecycle"
    restart: unless-stopped
    expose:
      - 9090
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"

  nodeexporter:
    image: prom/node-exporter:v1.0.1
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.rootfs=/rootfs"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)"
    restart: unless-stopped
    expose:
      - 9100
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"

  grafana:
    image: grafana/grafana:7.0.5
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=user
      - GF_SECURITY_ADMIN_PASSWORD=Sparta212
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    expose:
      - 3000
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"
